baseURL = 'https://lapis.self.starrypoint.me/'
languageCode = 'en-us'
title = '~lapis/'
theme = 'alageek'
enableEmoji = true

[menus]

  [[menus.primary]]
    identifier = "who"
    name = "Who?"
    url = "/who/"
    weight = 10
    
  [[menus.primary]]
    identifier = "what"
    name = "What?"
    url = "/what/"
    weight = 20
    
  [[menus.primary]]
    identifier = "when"
    name = "When?"
    url = "/when/"
    weight = 30
    
  [[menus.secondary]]
    identifier = "where"
    name = "Where?"
    url = "/where/"
    weight = 10
    
  [[menus.secondary]]
    identifier = "why"
    name = "Why?"
    url = "/why/"
    weight = 20
    
  [[menus.secondary]]
    identifier = "how"
    name = "How?"
    url = "/how/"
    weight = 30

[params]
copyright = "(c) 2023 Lapis Lazuli"
copyrightUrl = "https://starrypoint.me"
logofile = "img/logo.png"
highlightjs = true
progressively = true
uselatex = true
latestpostcount = 5
github = "vrnavi"
email = "lapis@starrypoint.me"
# twitter = "example"
mastodon_url = 'https://example.com'

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
